/* eslint-disable @typescript-eslint/naming-convention */

/**
 * Consolidated TreeItemType enum for all AWS services in the workbench.
 * Each type is prefixed with the service name for clarity and to avoid conflicts.
 */
export enum TreeItemType {
	// S3 Service
	S3Bucket = 1,
	S3Shortcut = 2,

	// Lambda Service
	LambdaFunction = 100,
	LambdaCode = 101,
	LambdaLogGroup = 102,
	LambdaLogStream = 103,
	LambdaTriggerGroup = 104,
	LambdaTriggerSavedPayload = 105,
	LambdaCodePath = 106,
	LambdaTriggerNoPayload = 107,
	LambdaTriggerWithPayload = 108,
	LambdaTriggerFilePayload = 109,
	LambdaResponsePayload = 110,
	LambdaEnvironmentVariableGroup = 111,
	LambdaEnvironmentVariable = 112,
	LambdaTagsGroup = 113,
	LambdaTag = 114,
	LambdaInfoGroup = 115,
	LambdaInfoItem = 116,

	// SQS Service
	SQSQueue = 200,
	SQSPublishGroup = 201,
	SQSPublishAdhoc = 202,
	SQSPublishFile = 203,
	SQSReceiveGroup = 204,
	SQSReceivedMessage = 205,
	SQSDetailGroup = 206,
	SQSDetailItem = 207,
	SQSPolicy = 208,
	SQSDeletedMessage = 209,
	SQSOther = 299,

	// IAM Service
	IAMRole = 300,
	IAMPermissionsGroup = 301,
	IAMPermission = 302,
	IAMTrustRelationshipsGroup = 303,
	IAMTrustRelationship = 304,
	IAMTagsGroup = 305,
	IAMTag = 306,
	IAMInfoGroup = 307,
	IAMInfoItem = 308,

	// SNS Service
	SNSTopic = 400,
	SNSPublishGroup = 401,
	SNSPublishAdhoc = 402,
	SNSPublishFile = 403,
	SNSSubscriptionGroup = 404,
	SNSSubscription = 405,
	SNSOther = 499,

	// DynamoDB Service
	DynamoDBTable = 500,
	DynamoDBCode = 501,
	DynamoDBLogGroup = 502,
	DynamoDBLogStream = 503,
	DynamoDBTriggerGroup = 504,
	DynamoDBTriggerSavedPayload = 505,
	DynamoDBCodePath = 506,
	DynamoDBTriggerNoPayload = 507,
	DynamoDBTriggerWithPayload = 508,
	DynamoDBTriggerFilePayload = 509,
	DynamoDBResponsePayload = 510,
	DynamoDBEnvironmentVariableGroup = 511,
	DynamoDBEnvironmentVariable = 512,
	DynamoDBPrimaryKey = 513,
	DynamoDBPartitionKey = 514,
	DynamoDBSortKey = 515,
	DynamoDBCapacity = 516,
	DynamoDBTableInfo = 517,
	DynamoDBIndexes = 518,
	DynamoDBIndex = 519,
	DynamoDBTableSize = 520,
	DynamoDBItemCount = 521,
	DynamoDBTableClass = 522,
	DynamoDBTableStatus = 523,
	DynamoDBReadCapacity = 524,
	DynamoDBWriteCapacity = 525,
	DynamoDBTags = 526,
	DynamoDBTagItem = 527,
	DynamoDBCapacityExplanation = 528,
	DynamoDBTableArn = 529,
	DynamoDBAverageItemSize = 530,

	// Step Functions Service
	StepFunctionsStateMachine = 600,
	StepFunctionsCode = 601,
	StepFunctionsLogGroup = 602,
	StepFunctionsLogStream = 603,
	StepFunctionsTriggerGroup = 604,
	StepFunctionsTriggerSavedPayload = 605,
	StepFunctionsCodePath = 606,
	StepFunctionsTriggerNoPayload = 607,
	StepFunctionsTriggerWithPayload = 608,
	StepFunctionsTriggerFilePayload = 609,
	StepFunctionsResponsePayload = 610,
	StepFunctionsEnvironmentVariableGroup = 611,
	StepFunctionsEnvironmentVariable = 612,
	StepFunctionsExecutionGroup = 613,
	StepFunctionsExecution = 614,
	StepFunctionsSuccessfulExecutionGroup = 615,
	StepFunctionsFailedExecutionGroup = 616,
	StepFunctionsRunningExecutionGroup = 617,

	// Glue Service
	GlueJob = 700,
	GlueRunGroup = 701,
	GlueLogGroup = 702,
	GlueLogStream = 703,
	GlueRun = 704,
	GlueDetail = 705,
	GlueArguments = 706,
	GlueInfo = 707,

	// CloudWatch Service
	CloudWatchRegion = 800,
	CloudWatchLogGroup = 801,
	CloudWatchLogStream = 802,
	CloudWatchInfo = 803,
	CloudWatchInfoDetail = 804,
	CloudWatchToday = 805,
	CloudWatchYesterday = 806,
	CloudWatchHistory = 807,
	CloudWatchRefreshAction = 808,
}
